### ISSUE TITLE
The pseudo label does not exist. How to generate a pseudo label?

### ISSUE THREAD

**Issue by wanghangege** [refkxh/DUSA#1]
Hello distinguished researcher, I have a problem with pseudo labels not existing, can you help me?
FileNotFoundError: [Errno 2] No such file or directory: '/DUSA/data/cooperative-vehicle-infrastructure/pseudo-label/0/009055.json'

**Comment by refkxh** [comment]
Hi! To generate pseudo labels, you may first train a model on the simulated dataset and then run the inference script on the real-world dataset with the `save_pseudo_label` argument provided.
